language: node_js
node_js:
- lts/boron
- node
after_script: bash <(curl -s https://codecov.io/bash)
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: 0QmtWwtU8dvxZht4Hrx7NU8LfyPU2kgpRjx1VuIGfP5xGirvXssCU+DmbUTS14Ubr5CTViEy5/9ISy/SKhP2okfclkrx7wawuT2Fy3/ZsPZlWMRZSPokOprXrM+NU7A8kR5ZIc2P9MZUPYEkgLhgkC92iQvW+A6/J56mg/pRPp98qmb/zn9b5ycDvRhwIAa/Z0/BSwnBHEgLy0qE2bCynE1rs25KZX9pHMu9gpQeJiFjmVC88AkTgPGcObt0hJzGqq5AR4XO20FWeS0hXnYbFkn9QwfQp4SXMH5T/lrgNAVJCQQBNoZib23ieeMl17nYonXTbh5McFHxEcXuDTSAoUGZ1gqASrXvABn/XtYJFy6HkCvz5VGqW/nUQQZ589lsCO7OsRPYbC8A57vamWizevRE08btixVcUhQXe0oodLytRBWwbgC0GMNQyFe2A9b89R7iC796vtby0ktRWLLMWB2uwxPBx1ZbWjLMsmvztCC0Eited5Z/s/TeYCx1VN/WpbvFBsBeiahuwJee4ndQvjArmUzBQKBfyvlSZOpjUHhhI6OmwmPk+t5v1BBeYtyx9oQZkq4J/1PsUO2FumO80ZXay1VZf1JkbCgYtAX6xCrRA4shs1OTEx/0zM2ZIKWgDjMWLV/Ei1KhLNNSgDeuR8YiloCOBs4rHgKEfW5ME78=
  file:
    - "remark-gemoji.js"
    - "remark-gemoji.min.js"
  on:
    tags: true
